name: Health check

on:
    schedule:
        - cron: '0 0 1 1-12 *'

jobs:
    health_check_job:
        runs-on: ubuntu-20.04
        steps:
            - name: health check
              uses: jtalk/url-health-check-action@v3
              with:
                  # Check the following URLs one by one sequentially
                  url: https://pokedex-lywb.onrender.com/health
